/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package UX_UI;

/**
 *
 * @author phamhuy
 */
public class JDialogBinhLuan extends javax.swing.JDialog {

    /**
     * Creates new form JDialogBinhLuan
     */
    public JDialogBinhLuan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        lblUserIMG = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtUserComment = new javax.swing.JTextArea();
        btnUpload = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnUserStar1 = new javax.swing.JButton();
        btnUserStar2 = new javax.swing.JButton();
        btnUserStar3 = new javax.swing.JButton();
        btnUserStar4 = new javax.swing.JButton();
        btnUserStar5 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        lblBLIMG = new javax.swing.JLabel();
        lblBLName = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtBinhLuan = new javax.swing.JTextArea();
        lblBLStar1 = new javax.swing.JLabel();
        lblBLStar2 = new javax.swing.JLabel();
        lblBLStar3 = new javax.swing.JLabel();
        lblBLStar4 = new javax.swing.JLabel();
        lblBLStar5 = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnEnd = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lblBLIMG1 = new javax.swing.JLabel();
        lblBLName1 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtBinhLuan1 = new javax.swing.JTextArea();
        lblBLStar6 = new javax.swing.JLabel();
        lblBLStar7 = new javax.swing.JLabel();
        lblBLStar8 = new javax.swing.JLabel();
        lblBLStar9 = new javax.swing.JLabel();
        lblBLStar10 = new javax.swing.JLabel();
        btnEdit1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(0, 3));
        setSize(new java.awt.Dimension(0, 5));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backward.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nhận xét từ độc giả");

        jSeparator1.setMinimumSize(new java.awt.Dimension(0, 4));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        lblUserIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/github50.png"))); // NOI18N

        lblUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserName.setText("HuyDZ");

        txtUserComment.setColumns(20);
        txtUserComment.setLineWrap(true);
        txtUserComment.setRows(5);
        txtUserComment.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtUserComment);

        btnUpload.setText("Bình luận");

        btnCancel.setText("Huỷ");

        btnUserStar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png"))); // NOI18N
        btnUserStar1.setText("1");
        btnUserStar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserStar1ActionPerformed(evt);
            }
        });

        btnUserStar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png"))); // NOI18N
        btnUserStar2.setText("2");
        btnUserStar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserStar2ActionPerformed(evt);
            }
        });

        btnUserStar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png"))); // NOI18N
        btnUserStar3.setText("3");
        btnUserStar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserStar3ActionPerformed(evt);
            }
        });

        btnUserStar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png"))); // NOI18N
        btnUserStar4.setText("4");
        btnUserStar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserStar4ActionPerformed(evt);
            }
        });

        btnUserStar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png"))); // NOI18N
        btnUserStar5.setText("5");
        btnUserStar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserStar5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblUserIMG)
                    .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnUserStar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUserStar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUserStar3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUserStar4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUserStar5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpload)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lblUserIMG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserName)
                    .addComponent(btnUpload)
                    .addComponent(btnCancel)
                    .addComponent(btnUserStar1)
                    .addComponent(btnUserStar2)
                    .addComponent(btnUserStar3)
                    .addComponent(btnUserStar4)
                    .addComponent(btnUserStar5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        lblBLIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/github50.png"))); // NOI18N

        lblBLName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBLName.setText("HuyDZ");

        txtBinhLuan.setEditable(false);
        txtBinhLuan.setColumns(20);
        txtBinhLuan.setLineWrap(true);
        txtBinhLuan.setRows(5);
        txtBinhLuan.setText("Cuốn sách này rất ấn tượng với tôi về cách tác giả tận dụng ngôn ngữ để mô tả tình cảm và tâm lý nhân vật. Mỗi trang sách là một hành trình khám phá sâu sắc về con người và xã hội. Tôi thích cách tác giả xây dựng các nhân vật phức tạp, tạo nên những mối quan hệ đầy thăng trầm. Ngoài ra, lối viết của ông/ bà cũng rất lôi cuốn và dễ hiểu, không làm mất đi sự chân thực của câu chuyện. Cuốn sách này đưa tôi vào thế giới tưởng tượng một cách sống động, khiến tôi không thể dừng lại khi đã bắt đầu. Tôi tin rằng độc giả khác cũng sẽ tận hưởng và suy ngẫm nhiều về cuộc sống từ tác phẩm này như tôi đã trải qua.");
        txtBinhLuan.setWrapStyleWord(true);
        jScrollPane4.setViewportView(txtBinhLuan);

        lblBLStar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png"))); // NOI18N

        lblBLStar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png"))); // NOI18N

        lblBLStar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png"))); // NOI18N

        lblBLStar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png"))); // NOI18N

        lblBLStar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty-small-star-16.png"))); // NOI18N

        btnEdit.setText("Edit");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBLIMG)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblBLName, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblBLStar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBLStar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBLStar3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBLStar4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBLStar5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEdit)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblBLName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBLStar1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblBLStar2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblBLStar3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblBLStar4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblBLStar5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addComponent(lblBLIMG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEdit)))
                .addContainerGap())
        );

        btnStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/skip-to-start-16.png"))); // NOI18N

        btnPrevious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rewind-16.png"))); // NOI18N

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fast-forward-16.png"))); // NOI18N

        btnEnd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/end-16.png"))); // NOI18N

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));

        lblBLIMG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/github50.png"))); // NOI18N

        lblBLName1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBLName1.setText("HuyDZ");

        txtBinhLuan1.setEditable(false);
        txtBinhLuan1.setColumns(20);
        txtBinhLuan1.setLineWrap(true);
        txtBinhLuan1.setRows(5);
        txtBinhLuan1.setText("Cuốn sách này rất ấn tượng với tôi về cách tác giả tận dụng ngôn ngữ để mô tả tình cảm và tâm lý nhân vật. Mỗi trang sách là một hành trình khám phá sâu sắc về con người và xã hội. Tôi thích cách tác giả xây dựng các nhân vật phức tạp, tạo nên những mối quan hệ đầy thăng trầm. Ngoài ra, lối viết của ông/ bà cũng rất lôi cuốn và dễ hiểu, không làm mất đi sự chân thực của câu chuyện. Cuốn sách này đưa tôi vào thế giới tưởng tượng một cách sống động, khiến tôi không thể dừng lại khi đã bắt đầu. Tôi tin rằng độc giả khác cũng sẽ tận hưởng và suy ngẫm nhiều về cuộc sống từ tác phẩm này như tôi đã trải qua.");
        txtBinhLuan1.setWrapStyleWord(true);
        jScrollPane6.setViewportView(txtBinhLuan1);

        lblBLStar6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png"))); // NOI18N

        lblBLStar7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png"))); // NOI18N

        lblBLStar8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png"))); // NOI18N

        lblBLStar9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png"))); // NOI18N

        lblBLStar10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty-small-star-16.png"))); // NOI18N

        btnEdit1.setText("Edit");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBLIMG1)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblBLName1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblBLStar6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBLStar7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBLStar8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBLStar9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBLStar10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEdit1)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblBLName1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBLStar6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblBLStar7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblBLStar8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblBLStar9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblBLStar10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addComponent(lblBLIMG1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEdit1)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(293, 293, 293)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(262, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBack)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnEnd)
                    .addComponent(btnNext)
                    .addComponent(btnPrevious)
                    .addComponent(btnStart))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserStar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserStar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserStar1ActionPerformed

    private void btnUserStar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserStar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserStar2ActionPerformed

    private void btnUserStar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserStar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserStar3ActionPerformed

    private void btnUserStar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserStar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserStar4ActionPerformed

    private void btnUserStar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserStar5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserStar5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogBinhLuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogBinhLuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogBinhLuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogBinhLuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogBinhLuan dialog = new JDialogBinhLuan(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEdit1;
    private javax.swing.JButton btnEnd;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnUpload;
    private javax.swing.JButton btnUserStar1;
    private javax.swing.JButton btnUserStar2;
    private javax.swing.JButton btnUserStar3;
    private javax.swing.JButton btnUserStar4;
    private javax.swing.JButton btnUserStar5;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblBLIMG;
    private javax.swing.JLabel lblBLIMG1;
    private javax.swing.JLabel lblBLName;
    private javax.swing.JLabel lblBLName1;
    private javax.swing.JLabel lblBLStar1;
    private javax.swing.JLabel lblBLStar10;
    private javax.swing.JLabel lblBLStar2;
    private javax.swing.JLabel lblBLStar3;
    private javax.swing.JLabel lblBLStar4;
    private javax.swing.JLabel lblBLStar5;
    private javax.swing.JLabel lblBLStar6;
    private javax.swing.JLabel lblBLStar7;
    private javax.swing.JLabel lblBLStar8;
    private javax.swing.JLabel lblBLStar9;
    private javax.swing.JLabel lblUserIMG;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTextArea txtBinhLuan;
    private javax.swing.JTextArea txtBinhLuan1;
    private javax.swing.JTextArea txtMoTa1;
    private javax.swing.JTextArea txtMoTa3;
    private javax.swing.JTextArea txtUserComment;
    // End of variables declaration//GEN-END:variables
}
