/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UX_UI;

import dao.AccessDAO;
import dao.NoiBoDAO;
import dao.PhongBanDAO;
import dao.SachDAO;
import java.util.ArrayList;
import java.util.List;
import library.DialogHelper;
import library.Extension;
import model.Sach;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class testAPI extends javax.swing.JFrame {

    /**
     * Creates new form testAPI
     */
    List<Sach> listSach = new ArrayList<>();
    SachDAO dao = new SachDAO();

    public testAPI() {
        initComponents();
        setLocationRelativeTo(null);
        btnSearch.addActionListener(e -> {
            String keyword = txtSearch.getText();
            listSach = Extension.getListSachfromOpenLibrary(keyword, 5, false, false);
            for (Sach s : listSach) {
                System.out.println(s.toString());
            }
            fillToLabel();
        });

        jButton1.addActionListener(e -> {
            addBook(1);
        });

        jButton2.addActionListener(e -> {
            addBook(2);
        });

        jButton3.addActionListener(e -> {
            addBook(3);
        });

        jButton4.addActionListener(e -> {
            addBook(4);
        });

        jButton5.addActionListener(e -> {
            addBook(5);
        });
    }

    final Integer sachCount = 5;
    int curPage = 1;

    private void addBook(int index) {
        if (listSach.get(index - 1) == null) {
            return;
        }
        Sach temp = listSach.get(index - 1);
        if (dao.selectByID(temp.getIdSach()) != null) {
            DialogHelper.alert(null, "Already existed!!");
            return;
        }

        dao.insert(temp);

        if (dao.selectByID(temp.getIdSach()) != null) {
            DialogHelper.alert(null, "Insert the book named: " + temp.getTenSach() + " successfully!!");
        } else {
            DialogHelper.alert(null, "The insertion should be successfully!");
        }
    }

    void fillToLabel() {
        for (int i = (curPage - 1) * sachCount; i < listSach.size() && i < curPage * sachCount; i++) {
            Sach sach = listSach.get(i);
            System.out.println(sach.getCoverI().substring(sach.getCoverI().lastIndexOf('/') + 1));
            switch (i % sachCount) {
                case (5 - 1) -> {
                    Extension.scaleImage(lblCover5, sach.getCoverI().substring(sach.getCoverI().lastIndexOf('/') + 1));
                    lblTenSach5.setText(sach.getTenSach());
//                    pnlSach5.setVisible(true);
                }
                case (4 - 1) -> {
                    Extension.scaleImage(lblCover4, sach.getCoverI().substring(sach.getCoverI().lastIndexOf('/') + 1));
                    lblTenSach4.setText(sach.getTenSach());
//                    pnlSach4.setVisible(true);
                }
                case (3 - 1) -> {
                    Extension.scaleImage(lblCover3, sach.getCoverI().substring(sach.getCoverI().lastIndexOf('/') + 1));
                    lblTenSach3.setText(sach.getTenSach());
//                    pnlSach3.setVisible(true);
                }
                case (2 - 1) -> {
                    Extension.scaleImage(lblCover2, sach.getCoverI().substring(sach.getCoverI().lastIndexOf('/') + 1));
                    lblTenSach2.setText(sach.getTenSach());
//                    pnlSach2.setVisible(true);
                }
                case (1 - 1) -> {
                    Extension.scaleImage(lblCover1, sach.getCoverI().substring(sach.getCoverI().lastIndexOf('/') + 1));
                    lblTenSach1.setText(sach.getTenSach());
//                    pnlSach1.setVisible(true);
                }
                default -> {
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        pnlSach1 = new javax.swing.JPanel();
        lblCover1 = new javax.swing.JLabel();
        lblTenSach1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pnlSach2 = new javax.swing.JPanel();
        lblCover2 = new javax.swing.JLabel();
        lblTenSach2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        pnlSach3 = new javax.swing.JPanel();
        lblCover3 = new javax.swing.JLabel();
        lblTenSach3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        pnlSach4 = new javax.swing.JPanel();
        lblCover4 = new javax.swing.JLabel();
        lblTenSach4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        pnlSach5 = new javax.swing.JPanel();
        lblCover5 = new javax.swing.JLabel();
        lblTenSach5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INSERT BOOK FORM");

        btnSearch.setText("Search");

        pnlSach1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCover1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTenSach1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTenSach1.setText("Tên sách");
        lblTenSach1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton1.setText("Add");

        javax.swing.GroupLayout pnlSach1Layout = new javax.swing.GroupLayout(pnlSach1);
        pnlSach1.setLayout(pnlSach1Layout);
        pnlSach1Layout.setHorizontalGroup(
            pnlSach1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSach1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSach1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCover1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(lblTenSach1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSach1Layout.setVerticalGroup(
            pnlSach1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSach1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCover1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTenSach1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlSach2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCover2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTenSach2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTenSach2.setText("Tên sách");
        lblTenSach2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton2.setText("Add");

        javax.swing.GroupLayout pnlSach2Layout = new javax.swing.GroupLayout(pnlSach2);
        pnlSach2.setLayout(pnlSach2Layout);
        pnlSach2Layout.setHorizontalGroup(
            pnlSach2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSach2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSach2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSach2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlSach2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTenSach2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCover2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlSach2Layout.setVerticalGroup(
            pnlSach2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSach2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCover2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTenSach2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlSach3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCover3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTenSach3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTenSach3.setText("Tên sách");
        lblTenSach3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton3.setText("Add");

        javax.swing.GroupLayout pnlSach3Layout = new javax.swing.GroupLayout(pnlSach3);
        pnlSach3.setLayout(pnlSach3Layout);
        pnlSach3Layout.setHorizontalGroup(
            pnlSach3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSach3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSach3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSach3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblTenSach3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCover3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlSach3Layout.setVerticalGroup(
            pnlSach3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSach3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCover3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTenSach3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        pnlSach4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCover4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTenSach4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTenSach4.setText("Tên sách");
        lblTenSach4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton4.setText("Add");

        javax.swing.GroupLayout pnlSach4Layout = new javax.swing.GroupLayout(pnlSach4);
        pnlSach4.setLayout(pnlSach4Layout);
        pnlSach4Layout.setHorizontalGroup(
            pnlSach4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSach4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSach4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCover4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTenSach4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlSach4Layout.setVerticalGroup(
            pnlSach4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSach4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCover4, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTenSach4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        pnlSach5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCover5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTenSach5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTenSach5.setText("Tên sách");
        lblTenSach5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton5.setText("Add");

        javax.swing.GroupLayout pnlSach5Layout = new javax.swing.GroupLayout(pnlSach5);
        pnlSach5.setLayout(pnlSach5Layout);
        pnlSach5Layout.setHorizontalGroup(
            pnlSach5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSach5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSach5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSach5Layout.createSequentialGroup()
                        .addGroup(pnlSach5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCover5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTenSach5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlSach5Layout.setVerticalGroup(
            pnlSach5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSach5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCover5, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTenSach5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSach1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlSach2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlSach3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlSach4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlSach5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlSach1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSach2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSach3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSach4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSach5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearch)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(testAPI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(testAPI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(testAPI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(testAPI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new testAPI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCover1;
    private javax.swing.JLabel lblCover2;
    private javax.swing.JLabel lblCover3;
    private javax.swing.JLabel lblCover4;
    private javax.swing.JLabel lblCover5;
    private javax.swing.JLabel lblTenSach1;
    private javax.swing.JLabel lblTenSach2;
    private javax.swing.JLabel lblTenSach3;
    private javax.swing.JLabel lblTenSach4;
    private javax.swing.JLabel lblTenSach5;
    private javax.swing.JPanel pnlSach1;
    private javax.swing.JPanel pnlSach2;
    private javax.swing.JPanel pnlSach3;
    private javax.swing.JPanel pnlSach4;
    private javax.swing.JPanel pnlSach5;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
